<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Run as you type command parameters syntax file</string>
	<key>name</key>
	<string>RunAsYouType</string>
	<key>fileTypes</key>
	<array>
		<string>rayt</string>
	</array>
	<key>scopeName</key>
	<string>rayt</string>
	<key>uuid</key>
	<string>59864b2e-8a00-418f-8c27-2d2e090ab08a</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#kwords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#str-double</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#str-single</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\-|\/)+</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#val</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#key</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#str-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#str-single</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>support.function</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#obj</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>key</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z0-9]+</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<key>class</key>
		<dict>
			<key>match</key>
			<string>\.[\w\d-_-]+</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<key>kwords</key>
		<dict>
			<key>match</key>
			<string>\b(sql|select|insert|update|remove|delete|drop|from|to)\b</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>((#|\/\/|\;\;).+)|(\/\*.*\*\/)</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>&lt;|&gt;|\=|\*|\/|\-|\+|\:|\^|\?|\|</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<key>repeat_quantifier</key>
		<dict>
			<key>match</key>
			<string>\d</string>
			<key>name</key>
			<string>keyword.quantifier</string>
		</dict>
		<key>str-double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<key>str-single</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<key>val</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\=|\:)[.\d\w]+</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<key>obj</key>
		<dict>
			<key>match</key>
			<string>[^\}]+</string>
			<key>name</key>
			<string>support.class</string>
		</dict>
	</dict>
</dict>
</plist>